// Vue/vue-project/src/components/ui/Select.vue
<template>
  <select :value="modelValue" @change="$emit('update:modelValue', $event.target.value)">
    <option value="" disabled>Выберите из списка</option>
    <option
      :value="option.value"
      v-for="option in options"
      :key="option.value"
    >
      {{ option.name }}
    </option>
  </select>
</template>

<script>
  export default {
    name: "Select",

    props: {
      modelValue: {
        type: String
      },
      options: {
        type: Array,
        default: () => []
      }
    }
  }
</script>

<style scoped>

</style>

// React/react_fundamental/src/components/Select/SelectComponent.jsx
import React from 'react'

const SelectComponent = ({ options, defaultValue, value, onChange }) => {
  return (
    <select value={value} onChange={(event) => onChange(event.target.value)}>
      <option disabled value="">
        {defaultValue}
      </option>
      {options.map((option) => (
        <option key={option.value} value={option.value}>
          {option.name}
        </option>
      ))}
    </select>
  )
}

export default SelectComponent
